name: "CI/CD Jobs"
on: [push, pull_request]
jobs: 
  publish-snapshot:
    if: contains('refs/heads/main', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: Publish Snapshot
        run: echo "I'm the main branch"
